
oneway
Array ( [booking] => air [trip_type] => oneway [cash_adv] => 9000 [purpose_of_visit] => required [onwardcity] => Array ( [0] => [1] => [2] => 1303 ) [travel_to] => Array ( [0] => [1] => [2] => 1302 ) [date] => Array ( [0] => [1] => [2] => 2017-06-25 ) [book_airline] => Array ( [0] => [1] => [2] => [3] => 9 ) [preferred_airline_time] => Array ( [0] => [1] => [2] => [3] => 2 ) [pref_hotel] => Array ( [0] => [1] => [2] => 13 ) [late_checkin_date] => Array ( [0] => [1] => [2] => 2017-07-25 ) [late_checkout_date] => Array ( [0] => [1] => [2] => 2017-06-27 ) [car_company] => Array ( [0] => [1] => [2] => [3] => 4 ) [airport_pickup_loca] => Array ( [0] => [1] => [2] => [3] => xxx ) [airport_drop_loca] => Array ( [0] => [1] => [2] => [3] => ) [pickupcity] => Array ( [0] => [1] => [2] => [3] => ) [car_type] => Array ( [0] => [1] => [2] => [3] => car ) [car_size] => Array ( [0] => [1] => [2] => [3] => small ) [rdate] => Array ( [0] => [1] => ) [late_checkin] => Array ( [0] => yes ) [late_checkout] => Array ( [0] => yes ) [airport_drop] => Array ( [0] => yes ) [need_car] => Array ( [0] => yes ) [special_mention] => required ) 


round trip 

Array ( [booking] => air [trip_type] => round trip [cash_adv] => 9000 [purpose_of_visit] => required [onwardcity] => Array ( [0] => [1] => 417 [2] => ) [travel_to] => Array ( [0] => [1] => 417 [2] => ) [date] => Array ( [0] => [1] => 2017-06-25 [2] => ) [book_airline] => Array ( [0] => [1] => 5 [2] => 1 [3] => ) [preferred_airline_time] => Array ( [0] => [1] => 6 [2] => 2 [3] => ) [pref_hotel] => Array ( [0] => [1] => 2 [2] => ) [late_checkin_date] => Array ( [0] => [1] => 2017-06-25 [2] => ) [late_checkout_date] => Array ( [0] => [1] => 2017-07-30 [2] => ) [car_company] => Array ( [0] => [1] => 1 [2] => 1 [3] => ) [airport_pickup_loca] => Array ( [0] => [1] => xxx [2] => [3] => ) [airport_drop_loca] => Array ( [0] => [1] => [2] => yyy [3] => ) [pickupcity] => Array ( [0] => [1] => [2] => [3] => ) [car_type] => Array ( [0] => [1] => taxi [2] => taxi [3] => ) [car_size] => Array ( [0] => [1] => small [2] => small [3] => ) [rdate] => Array ( [0] => 2017-06-27 [1] => 2017-06-27 ) [late_checkin] => Array ( [0] => yes ) [late_checkout] => Array ( [0] => yes ) [airport_drop] => Array ( [0] => yes ) [need_car] => Array ( [0] => yes [1] => yes ) [airport_pickup] => Array ( [0] => yes ) [special_mention] => required ) 

multicity
Array ( [booking] => air [trip_type] => multicity [cash_adv] => 9000 [purpose_of_visit] => Purpose of visit [onwardcity] => Array ( [0] => [1] => [2] => 1303 [3] => 494 ) [travel_to] => Array ( [0] => [1] => [2] => 916 [3] => 783 ) [date] => Array ( [0] => [1] => [2] => 2017-07-25 [3] => 2017-07-25 ) [book_airline] => Array ( [0] => [1] => [2] => [3] => 2 [4] => 9 ) [preferred_airline_time] => Array ( [0] => [1] => [2] => [3] => 4 [4] => 2 ) [pref_hotel] => Array ( [0] => [1] => [2] => 2 [3] => 10 ) [late_checkin_date] => Array ( [0] => [1] => [2] => 2017-07-25 [3] => 2017-07-25 ) [late_checkout_date] => Array ( [0] => [1] => [2] => 2017-07-30 [3] => 2017-07-30 ) [car_company] => Array ( [0] => [1] => [2] => [3] => 2 [4] => 2 ) [airport_pickup_loca] => Array ( [0] => [1] => [2] => [3] => xxx [4] => xxx1 ) [airport_drop_loca] => Array ( [0] => [1] => [2] => [3] => [4] => ) [pickupcity] => Array ( [0] => [1] => [2] => [3] => [4] => ) [car_type] => Array ( [0] => [1] => [2] => [3] => car [4] => car1 ) [car_size] => Array ( [0] => [1] => [2] => [3] => mid [4] => mid1 ) [rdate] => Array ( [0] => [1] => ) [late_checkin] => Array ( [0] => yes [1] => yes ) [late_checkout] => Array ( [0] => yes [1] => yes ) [airport_drop] => Array ( [0] => yes [1] => yes ) [need_car] => Array ( [0] => yes [1] => yes ) [special_mention] => Purpose of visit ) 
